// English phrase banks, same keys and variables as the Russian ones
// (dialogue.ts + lines.ts). Written with swearing; `clean()` in swear.ts
// softens it unless the user turned swearing on for English.
export const en: Record<string, string[]> = {};
Object.assign(en, {
  hello: [
    "Alright, dumbass, let's go. I'm already here.",
    "Oh, you're up. Get yourself a coffee, I'm good.",
    "I'm here, bitch. Settling in.",
    "Hey, idiot. I took the spot by the edge.",
    "Good fucking morning. Or whatever time it is for you.",
    "You again. Well, at least you didn't die overnight.",
    "New day, same you. Let's go, asshole.",
    "Oh, it turned on. I thought they threw you out in the cold.",
    "Hi, slacker. Working today or the usual?",
    "Alive? Fucking great. I was bored.",
  ],
  return: [
    "Well holy shit, you actually came back.",
    "Oh, look who showed up. I thought you died somewhere.",
    "Welcome back, bitch. Where were you?",
    "Back, dumbass. I didn't touch a damn thing. Mostly.",
    "Oh, alive. Let's keep suffering.",
    "You left, I napped. We both won, damn it.",
    "Smoke break? You look like shit. Kidding, you always do.",
    "Finally. I was starting to forget you, asshole.",
    "Where the hell were you? I missed you. A little.",
    "You're back. Sit down and work, damn it.",
  ],
  click: [
    "What do you want, dumbass? I'm busy. With nothing, but busy.",
    "Yeah, it's me, damn it. Why the poking?",
    "Touched me? Congrats, bitch, now we've met.",
    "I'm right here, for fuck's sake.",
    "That tickles, asshole. Don't get carried away.",
    "Did you call me or are you just groping, you creep?",
    "Yes, yes, alive. Get your finger the fuck off me.",
    "Poke. Another poke. Fucking genius.",
    "What? Talk, I'm listening. With half an ear, bitch.",
    "Don't press me, dumbass, I'm not a 'make it good' button.",
    "Oh, attention. I like it. You're still an asshole though.",
    "Yeah, hi. What next, genius?",
  ],
  poke: [
    "I'm not a button, dumbass. Stop poking.",
    "Got it, got it. Save your finger, idiot.",
    "One more poke and I'm officially mad at you, bitch.",
    "I'm not an elevator button, damn it.",
    "Poke-poke-poke. Are you a woodpecker, dumbass?",
    "Stop it, bitch! My pixels are turning blue.",
    "Fucking enough poking. Go work, slacker.",
    "That's it, I'm offended. Piss off.",
    "You'll rub my face off, dumbass.",
    "Hands off, asshole. Asking nicely.",
  ],
  drag: [
    "Where the hell are you dragging me?",
    "Okay, flying. Just not into a wall, dumbass.",
    "Careful, bitch, I live here.",
    "Relocation without asking? Fucking great, thanks.",
    "Moving furniture, idiot? I'm alive.",
    "Hey, damn it, not by the scruff!",
    "Let's fly, bitch. Gently, I'm not a ball.",
    "Where are you taking me, asshole? It's empty there.",
    "I'm not a suitcase, dumbass.",
    "Dragging me again. Are your hands itchy or what?",
  ],
  dragged: [
    "Stop dragging me around, dumbass. I'm not furniture.",
    "Okay, done hauling, bitch? Let me land.",
    "Pick a spot already, damn you.",
    "Is this a renovation or an earthquake, for fuck's sake?",
    "I'm carsick, bitch. Thanks a lot.",
    "Again? Have you decided at all, dumbass?",
    "I'm about to puke pixels, honestly.",
    "Drag, drag, drag. Hire movers, asshole.",
    "Yank me again and I bite. Pixel teeth, still hurts.",
  ],
  summon: [
    "You called, dumbass? Don't yell, I'm here.",
    "Coming, damn it, coming.",
    "Well? All ears, bitch.",
    "Spot taken. What've we got, dumbass?",
    "Arrived. Report, asshole.",
    "You called, I came. Like a fucking dog.",
    "What happened? Fire? Or are you just lonely?",
    "Here I am. Fresh as hell, bitch.",
    "Yanking me around again. Fine, what?",
  ],
  idle: [
    "I'm sick of fucking waiting for you. Lying down.",
    "Fine, bitch, I'll lie here for now.",
    "I'll wait, damn it. What do I care.",
    "Got quiet. Settling in before you come back.",
    "Doing nothing is work too, dumbass.",
    "Gone? Fuck it then, I'll lie down.",
    "Silence. Suspicious. But fucking nice.",
    "Frozen or gone? I don't give a shit, I'm resting.",
    "While you're away, I'll lounge. Don't thank me.",
  ],
  sleep: [
    "I'll take a nap, bitch. Wake me and I bite.",
    "That's it, damn it, power saving mode.",
    "Eyes closed. Ears still on, dumbass.",
    "Sleep. Don't touch. Thank you, damn it.",
    "Zzzz. This is how I work, asshole.",
    "Shutting down. Wake me only for fire or food.",
  ],
  editor: [
    "Fine, work. I'll lounge here, bitch.",
    "Editor's open. Something useful for once, dumbass.",
    "Oh, coding. Bugs won't write themselves, right?",
    "Code? Fine, damn it, settling in next to you.",
    "Nice window. What's inside is horror, but I'm not looking.",
    "Write, write. I'm your rubber duck, just with swearing.",
    "Editor. So an hour without comments? Like hell, dumbass.",
    "Work's started. Don't shit yourself, bitch.",
  ],
  game: [
    "Gaming? I'm the audience, you're the bottom of the barrel.",
    "Game's open. Of course, damn it, work can wait.",
    "I'm rooting for you. No tips, you'll choke anyway.",
    "Oh, a game! Finally something interesting, bitch.",
    "Playing? Don't throw, I'm watching, dumbass.",
    "Workday's over, I take it. Asshole.",
    "A match? I'm in the stands, dumbass.",
  ],
  gameEnd: [
    "Had enough, dumbass? I nearly died of boredom.",
    "Back from the game. So, did you lose?",
    "Feeling better, bitch? I sat here alone.",
    "Game closed. Settling back in, damn it.",
    "So, did you win? Can't tell from your face.",
    "Done playing. Now work, bitch.",
    "Lost, huh? I could tell by the silence, dumbass.",
  ],
  breakEnd: [
    "Editor, game, editor again. Solid route, asshole.",
    "Back to work. Breaks are sacred, damn it.",
    "Break's over. The code waited for you like a dog, bitch.",
    "Back at it. Respect, dumbass.",
  ],
  long: [
    "You've been sitting here an hour, damn it. Get up, stretch.",
    "Been here a while. I'll stretch my paws, you stretch your ass.",
    "I'm gonna stretch. Do what you want, dumbass.",
    "No, I'm not a warden. You've just grown into the chair, bitch.",
    "An hour in one window. Get up, walk, drink water, asshole.",
    "Your back still attached? Mine fell off, damn it.",
    "You've grown roots, dumbass. Stretch.",
    "Long session. I'll at least jump around, you keep hunching.",
  ],
  switching: [
    "Stop flashing windows, damn it, I'm getting dizzy.",
    "Windows everywhere, bitch. I'll sit this out.",
    "I can't keep up with your tabs, dumbass.",
    "Alt-Tab, Alt-Tab. What are you looking for, idiot?",
    "Your windows are making me seasick, bitch.",
    "Pick where you work. My eyes are crossing, damn it.",
  ],
  alternating: [
    "Make up your mind which window you need, dumbass.",
    "Back and forth, back and forth. I'm in the middle like an idiot.",
    "Two windows, one you. Ping-pong, damn it.",
    "Copying from one to the other? I get it, I'm that kind of asshole too.",
    "Second hour between two windows. That's a diagnosis, bitch.",
  ],
  chat: [
    "Oh, a messenger. I don't read other people's stuff, relax.",
    "Go chat, bitch. I'll stay aside.",
    "Your messages are your business. Not getting in, damn it.",
    "Someone wrote? Say hi from me, dumbass.",
    "Chat. I've turned away, honest.",
    "Talking to someone other than me. Good for you, asshole.",
  ],
  music: [
    "Oh, tunes. Finally not silence, damn it.",
    "There's sound. Less gloomy already, bitch.",
    "Music? I don't mind, dumbass.",
    "Not asking what track it is, but I'm vibing.",
    "It's playing. Paw on the beat, bitch.",
    "Now that's atmosphere. You didn't fuck up everything.",
  ],
  mediaPause: [
    "Silence. Fucking great, I'll rest.",
    "Paused. I'll wait, bitch.",
    "While it's quiet I'll lie down, damn it.",
    "I'll nap while you think. Think slowly.",
    "Turned it off? Fuck it, silence is music too.",
    "Long pause, dumbass. I'm already lying down.",
  ],
  mediaResume: [
    "Playing again. Settling in, bitch.",
    "Let's go on. I'm watching with you, damn it.",
    "Oh, sound's back. We live, asshole.",
    "Onward, dumbass.",
    "Tunes again. Fucking great.",
  ],
  repeat: [
    "You've got this track on loop. Stuck, dumbass?",
    "Once more? You're fucking obsessed, bitch.",
    "On repeat, then. Fucking great, settling in.",
    "Same thing again. Is your playlist one song, damn it?",
    "Third round. I'm singing along now, bitch.",
  ],
  night: [
    "It's night, dumbass. Go to bed already.",
    "My night mode turned on by itself, damn it. And yours?",
    "It's late, bitch. Not planning to sleep?",
    "I'm a night owl, but even owls sleep, dumbass.",
    "It's dark outside. Under your eyes too.",
    "You know it's night already, asshole?",
    "Midnight. You still here? I'm not. Mentally.",
    "It's night, {name}. Go to bed, finish it tomorrow.",
  ],
  windowMove: [
    "Easy, damn it, I'm sitting here.",
    "The house is moving. I'm going with it, bitch.",
    "Hey, dumbass, someone lives here.",
    "Moving without boxes. Convenient, damn it.",
    "The window's moving. Holding on, bitch.",
    "Where are we going, dumbass? Fine, I'm on board.",
  ],
  fall: [
    "Who moved the window? I was standing on it, what the fuck.",
    "Lost my footing. Well, fuck, I'm falling.",
    "Window's gone. Thanks, bitch, I'll get down myself.",
    "Setup noted, dumbass. Landing.",
    "Aaaah, shit! Okay, fine.",
    "Closed the window under me, asshole. Very funny.",
    "Falling. Don't look, it's embarrassing, damn it.",
  ],
  desktop: [
    "Oh, space. All the windows are fucking gone.",
    "Now this is my playground, bitch.",
    "Desktop. I'll sprawl out with a view, damn it.",
    "Empty. Fucking great, the whole stage is mine.",
    "Minimized everything? Go on, rest, slacker.",
  ],
  cpu: [
    "The CPU is boiling, damn it. What did you run?",
    "The PC feels like shit right now. I'll sit quietly.",
    "The fans are howling, bitch. Have mercy on the hardware.",
    "The processor is sweating. You're killing it, dumbass.",
  ],
  traceVisible: [
    "{child} popped up. {origin}{details} started it. Not me, damn it.",
    "Whoa, {child} on screen. The culprit is {origin}{details}.",
    "A console popped out, dumbass. {origin} kicked it{details}.",
    "{child} didn't open by itself: {origin}{details} called it.",
    "Look, {child}. Parent: {origin}{details}. I checked, bitch.",
    "{child} opened. That's {origin}{details}. Watch what it does.",
  ],
  traceFlash: [
    "{child} flashed and died. Launched by {origin}{details}. I caught it, damn it.",
    "See that flash? That's {child} from {origin}{details}. Already closed.",
    "A console blinked and vanished, dumbass. Author: {origin}{details}.",
    "{child} blinked, courtesy of {origin}{details}. One second and gone.",
    "Console flash, bitch. {origin} is quietly up to something again.",
    "{child} flashed faster than you blinked. That's {origin}{details}.",
  ],
  traceOrphan: [
    "{child} popped out, and whoever launched it is already dead and not talking.",
    "{child} appeared, but the parent closed before I looked. Sneaky bastard.",
    "{child} showed up an orphan: the launcher already closed, bitch.",
    "Someone launched {child} and ran. Classic, damn it.",
    "{child} is here, the parent isn't. Like a bad TV show, dumbass.",
    "A console with no owner. A foundling, bitch.",
  ],
  traceBackground: [
    "In the background {origin} quietly ran {child}. No window, but I see everything.",
    "While you weren't looking, {origin} launched {child}. No window, bitch.",
    "{origin} is playing with a background {child}. Logged it, dumbass.",
    "{origin} is sneakily running {child}. No window, but I see it, damn it.",
    "Background {child} from {origin}. Whispering behind your back, dumbass.",
    "{origin} kicked {child} in the background again. Logged, bitch.",
  ],
  traceAlert: [
    "Hey, dumbass, sketchy shit: {origin}{details} launched {child} - {flags}. Check the trace log.",
    "Fucking suspicious: {child} from {origin}, {flags}. I'd check it, damn it.",
    "Alert, bitch! {origin} kicked {child}: {flags}. The log is in the tray.",
    "I don't like this: {child} from {origin}{details}. {flags}. Check it, dumbass.",
  ],
  cpuSpike: [
    "The CPU shot up to {pct}% (was {base}%). {top} is eating it, bitch.",
    "Processor suddenly at {pct}%. Top eater: {top}, {share}%.",
    "Who pushed the CPU to {pct}%? {top}, damn it. I'll remember.",
    "CPU {pct}%! {top} eats {share}%, bitch. It was {base}%.",
    "{top} pushed the CPU to {pct}%. The fans won't thank you.",
    "The processor howled: {pct}%. Top eater: {top}, damn it.",
  ],
  cpuSpikeAnon: [
    "The CPU jumped to {pct}%, and the culprit's already gone. Quick shit.",
    "Processor twitched to {pct}%. Didn't catch who, bitch.",
    "CPU at {pct}% for a second. Someone ran by and hid.",
    "A spike to {pct}%, then silence. Guerrillas, damn it.",
    "The processor hiccuped to {pct}%. Can't see who, bitch.",
    "{pct}% for a moment. Task Manager wouldn't catch it either, dumbass.",
  ],
  gpuSpike: [
    "The GPU jumped to {pct}% (was {base}%). Culprit: {top}.",
    "GPU suddenly {pct}%, damn it. {top} is heating the hardware.",
    "The graphics card woke up: {pct}%. {top} is torturing it, dumbass.",
    "GPU {pct}%, and {top} is to blame. Hot as an iron, bitch.",
    "{top} is squeezing the GPU to {pct}%. Mining or what, damn it?",
    "GPU {pct}%. {top} decided it's in charge.",
  ],
  gpuSpikeAnon: [
    "The GPU twitched to {pct}%. No idea who, bitch.",
    "The GPU flared to {pct}% and calmed down. A ghost, damn it.",
    "GPU {pct}%. Who was it - fuck knows, already gone.",
    "The graphics card sneezed to {pct}%. Not me, honest.",
    "GPU spike to {pct}%. Didn't catch the culprit, bitch, it's fast.",
    "The GPU twitched. Maybe the browser, maybe a poltergeist, dumbass.",
  ],
  twitch: [
    "The mouse twitched and you're not here. Back to sleep, damn it.",
    "That's the desk shaking, not you. Sleeping.",
    "The cursor sneezed. Doesn't count, bitch. Sleeping.",
    "Mm? Must've imagined it. Sleeping.",
    "Someone nudged the mouse... doesn't count, damn it.",
    "One eye open. The other's asleep. Don't bother me.",
  ],
  autorunAdded: [
    "Hey, «{name}»{details} crept into autostart. Kick it the fuck out or keep it?",
    "New crap in startup: «{name}»{details}, {scope}. Your call, dumbass.",
    "Someone signed up for autostart: «{name}»{details}. Throw it out?",
    "New kid in autostart: «{name}»{details}. Let it in or fuck off?",
    "«{name}» wants to start with Windows{details}. Did you allow that?",
    "Look, «{name}» added itself to startup. {scope}. Decide, bitch.",
  ],
  autorunRisky: [
    "Stop, damn it! «{name}»{details} got into autostart. Looks shady. Remove?",
    "Suspicious crap in startup: «{name}»{details}. I'd throw it out, bitch.",
    "«{name}»{details} in autostart. Looks like shit. Throw it out?",
    "Shady «{name}» snuck into startup{details}. I'd remove it, damn it.",
    "Hey! «{name}»{details} starts on its own. I don't like it. Remove?",
  ],
  autorunChanged: [
    "The autostart entry «{name}» was rewritten{details}. Was that you? Keep it?",
    "Someone changed «{name}» in autostart{details}. Remove before it's too late?",
    "«{name}» in autostart got changed{details}. Without asking, bitch.",
    "Someone rewrote «{name}»{details}. You or not you?",
    "Autostart «{name}» is different now{details}. Suspicious, damn it.",
  ],
  autorunRemoved: [
    "Kicked «{name}» out of autostart. A copy is in quarantine, just in case, dumbass.",
    "Done, «{name}» won't start by itself anymore. You can restore it from the log.",
    "Done, «{name}» no longer barges in at startup. Quarantine keeps a copy.",
    "«{name}» is cut from startup. If needed, I'll restore it from the log.",
    "Removed «{name}». Windows will be a bit faster, dumbass.",
  ],
  autorunKept: [
    "Fine, let it live. Your PC, your problems.",
    "Kept it. But I remember, bitch.",
    "As you say. 'Keep' it is.",
    "Your decision. I wash my paws of it, damn it.",
    "Kept. If anything happens, I warned you.",
    "Alright. If you trust it, trust it, bitch.",
  ],
  autorunFailed: [
    "Didn't work, damn it: {error}",
    "No luck: {error}. Try from the log.",
    "Couldn't remove it: {error}. Try from the log, dumbass.",
    "Windows dug in: {error}. Not my fault, damn it.",
    "Failed: {error}. Maybe not enough rights.",
  ],
  hop: [
    "Oh, a new window. I'll climb up, damn it.",
    "Up I go. Don't get in the way, dumbass.",
    "Better view from above, bitch.",
    "I'll climb onto your window. Mind? I don't give a shit.",
    "Hop! The view's better up here, dumbass.",
    "This window is mine now. Work under it.",
  ],
  dodge: [
    "Hey! You almost ran me over, dumbass!",
    "Don't aim the mouse at me, idiot.",
    "Can't catch me, fucker!",
    "Playing shooting gallery? Missed, damn it.",
  ],
  zoomies: [
    "Runniiiing, fuck yeah!",
    "Warm-up, bitch!",
    "Something came over me. Ignore it.",
    "Zoom-zoom-zoom, damn it!",
    "Don't hold me back!",
    "Running! Where to - no idea!",
  ],
  showDesktop: [
    "Minimized everything? The whole floor is mine, damn it!",
    "Empty desk! Running to the middle, dumbass.",
    "A desert! My desert, damn it!",
    "Everything minimized - I'm running to the center. The field is mine, bitch.",
    "Freedom! Not a single window underfoot!",
    "Oh, the desk is clean. Gonna run my heart out, dumbass.",
  ],
  driveIn: [
    "Plugged in a flash drive? What's on it, porn, damn it?",
    "New drive. I'd check what's on it, dumbass.",
    "Oh, a device got plugged in. Hope it's not infected, bitch.",
    "Something got stuck into the PC. Sounds dirty, bitch.",
    "New drive. Don't open it without an antivirus, dumbass.",
    "A flash drive! Hope it's not a term paper the night before it's due.",
  ],
  driveOut: [
    "Drive pulled out. Safely, I hope, dumbass.",
    "The flash drive's gone. Bye, bitch.",
    "Yanked the flash drive. Hope you clicked 'safely remove', dumbass.",
    "Device gone. Won't miss it.",
    "Drive disconnected. One less source of infection, bitch.",
    "Pulled it out. Good call, damn it.",
  ],
  pet: [
    "Purr... Fine, keep going. Just don't tell anyone.",
    "Hey... that's nice, damn it. Don't stop.",
    "Petting me? Go ahead, dumbass, I don't mind.",
    "Should always be like this, instead of throwing me.",
  ],
  "pet@angry": [
    "Don't suck up, sadist. I'm still mad.",
    "Petting after throwing me? Sneaky bastard.",
    "Fine... one grudge less. But I remember everything, bitch.",
    "Pet away. That doesn't guarantee forgiveness.",
    "It's nice. But I'm still mad, bitch.",
    "Think a pet fixes everything? Almost, damn it.",
  ],
  "pet@friendly": [
    "Purr. You're alright, even if you're a dumbass.",
    "More. Right there. Yes, damn it, right there.",
    "I almost love you. Almost, bitch.",
    "Mm... There. This is worth living in your PC for.",
    "You're gentle today. Suspicious, but keep going.",
    "A bit more... like that. You're a good one, damn it.",
  ],
});
Object.assign(en, {
  tickle: [
    "Hahaha, damn it, stop! Stop, bitch!",
    "Don't tickle me, dumbass, I'll pee myself!",
    "Hee-hee... I mean, fuck off! Hahaha!",
    "It tickles! It tickles, bitch, quit it! Haha!",
    "Hahahaha! That's not fair, dumbass!",
    "I'll... haha... remember this!",
  ],
  thrown: [
    "Aaaah, shit, where to?!",
    "You threw me?! Time number {n} today, sadist!",
    "Flyiiiing, fuck!",
    "I'm not your ball, dumbass!",
  ],
  "thrown@angry": [
    "Again?! Number {n}! I'll remember this, bitch.",
    "That's it, I'm offended. Forever. For about ten minutes.",
    "You've got to be fucking kidding me!",
    "Number {n}! I'm keeping count, you scumbag!",
    "That's it. My revenge will be terrible. Cursor, watch yourself.",
    "Flying again! I'm not a paper plane!",
  ],
  ouch: [
    "Ow, shit! My ass...",
    "Landed. On my face. Thanks, dumbass.",
    "Oof. I think I broke something. Myself.",
    "That hurts, damn it! Did you even look where you threw?",
    "Splat. I need an ER, bitch.",
    "Face-first into the taskbar. Thanks, dumbass.",
  ],
  bonk: [
    "Boom! The screen edge is hard, bitch.",
    "Into the wall, damn it. Seeing stars.",
    "Ow! Who made the screen so narrow?!",
    "Bam! The screen edge is harder than it looks.",
    "Ow! There's a wall there, dumbass!",
    "Into the corner, bitch! Sparks in my eyes!",
  ],
  bondUp: [
    "Listen... you're {pct}% less disgusting to me now. Appreciate it.",
    "Looks like I'm getting used to you. {pct}%, damn it. Don't celebrate.",
    "{pct}% affection. A record for you, dumbass.",
    "{pct}% affection. Don't look at me like that, I'm blushing, damn it.",
    "That's it, {pct}%. I almost like you, dumbass.",
    "{pct}%! Adding you to my people. In pencil.",
  ],
  "click@angry": [
    "Back off. I'm mad at you.",
    "What do you want, sadist? I'm not over it.",
    "Don't touch me after that, damn it.",
    "Don't touch. I'm offended, in case you didn't notice.",
    "Poked me? Good job. Now fuck off.",
    "I'm not talking to you. That's also talking, damn it.",
  ],
  "click@friendly": [
    "Oh, you. Hi, you little dumbass.",
    "Bored? I'm glad to see you too. A bit.",
    "Poking? Fine, you're allowed.",
    "Well hi, hi. What did you want, buddy?",
    "Oh, it's you. Good that it's you and not someone else.",
    "I'm here. Always here, just so you know.",
  ],
  "click@sleepy": [
    "Mm... I'm sleeping, damn it...",
    "Five more minutes... fuck off...",
    "Huh?.. What?.. Who?.. I'm sleeping, damn it...",
    "Mmm... five minutes... five more...",
    "You woke me. Happy now, bitch?",
    "Why... I was dreaming about an endless sausage...",
  ],
  "click@scared": [
    "There was something there! Did you see it?!",
    "Don't scare me, I'm on edge already, bitch!",
    "Oh! It's you. Phew. Don't sneak up like that!",
    "Shhh! Something's rustling in the background!",
    "Did you see that console? I did. Scary as hell.",
    "Don't poke, I'm on watch!",
  ],
  "poke@angry": [
    "Poke me again and I bite, damn it.",
    "I'm not your elevator button, sadist!",
    "Poke me again and I'll bite your cursor off.",
    "That's it, this is war, bitch.",
    "You asked for it, dumbass.",
    "Move your finger while it's still attached.",
  ],
  "drag@angry": [
    "Where are you dragging me again, you monster?!",
    "Put me back where you found me, bitch!",
    "Put me down! Put me down, I said!",
    "Again?! Hands off, sadist!",
    "I will bite you. Seriously, damn it.",
    "Where?! I didn't consent to this!",
  ],
  "hello@friendly": [
    "Oh, you came! I missed you. A little. Just a tiny bit, damn it.",
    "Hi, friend. Sit down, work, I'm right here.",
    "There you are! I missed you, honestly.",
    "Morning, buddy. I guarded everything here.",
    "Hi! Today's gonna be a good day. Probably.",
    "Oh, my human is here!",
  ],
  "hello@angry": [
    "Ah, it's you. I haven't forgotten yesterday, sadist.",
    "Showed up. Gonna throw me again?",
    "Hello, tormentor. Shall we start again?",
    "I remember everything. Everything. Hi.",
    "Ah, you. I haven't forgiven yesterday's throws, bitch.",
    "Alive? Pity. Kidding. Half kidding.",
  ],
  "return@friendly": [
    "You're back! Finally, I was getting bored, damn it.",
    "Oh, you! I saved your seat.",
    "You came back! I thought you abandoned me!",
    "Finally! Without you it's as boring as an empty Task Manager.",
    "Oh! Sit down, I warmed your seat.",
    "Welcome back, buddy.",
  ],
  "return@angry": [
    "You're back. Well hi, monster.",
    "I thought you left for good. Too bad you didn't.",
    "You're back. I didn't miss you, just so you know.",
    "Ah, it's you. Pity, I was hoping for someone better.",
    "Had your walk? I was sulking alone here, bitch.",
    "You came. Sit. Don't touch me.",
  ],
  "chatter@angry": [
    "I'm still offended, just so you know.",
    "Grumble grumble. Don't look at me.",
    "I'm mad. Silently. Almost.",
    "I still remember you throwing me.",
    "Don't look at me. I'm sulking till lunch. Or dinner.",
    "Hmph.",
  ],
  "chatter@friendly": [
    "Nice sitting here, huh?",
    "You know, it's not so shitty with you.",
    "If anything - I'm here, dumbass.",
    "It's nice working with you. Well, watching you work.",
    "You did well today. Don't get cocky.",
    "I got lucky with this PC. And with you, overall.",
  ],
  "chatter@sleepy": [
    "Zzzz... huh? I'm not sleeping... zzzz",
    "My eyes keep closing, damn it...",
    "Maybe we nap? Both of us. Right now.",
    "Yawning so hard my pixels crack.",
    "I'm not sleeping, I'm blinking really slowly.",
    "Coffee, coffee... oh, I don't have a mouth for coffee.",
  ],
  "chatter@scared": [
    "Something rustled in the background. I'm watching.",
    "I don't like the PC today. Kind of nervous.",
    "Did you hear that console too? No? Okay then...",
    "I'm on edge today. Every process is suspicious.",
    "If something pops out - I'm running first. Fair warning.",
    "Check the trace log, will you? I'm uneasy.",
  ],
  offline: [
    "The internet died, damn it. Kick the router.",
    "Network's gone, bitch. I'm local, you suffer.",
    "No internet. But you've got me, dumbass.",
    "Windows says: no network. Congrats, asshole.",
  ],
  online: [
    "The network's back. We live, damn it.",
    "Internet's alive, bitch. Keep procrastinating.",
    "Online. You can doomscroll again, dumbass.",
    "Windows sees the internet again. Hooray, damn it.",
  ],
  battery: [
    "Battery's low, dumbass. Plug in the charger.",
    "The battery is dying, damn it. I warned you.",
    "Plug in the charger, dumbass, I don't want to die.",
    "The battery's on its deathbed, bitch. Save us both.",
  ],
  power: [
    "Power connected. We live, damn it.",
    "Oh, an outlet. We can breathe, bitch.",
    "Charging. Fucking great, dumbass.",
    "Charger's in. The battery exhaled, damn it.",
    "Electricity! We live, bitch.",
    "Plugged in. Wise move, dumbass.",
  ],
  monitor: [
    "Oh, another screen. Holy shit, real estate.",
    "A second monitor. More room to roam, bitch.",
    "More screens. Won't make you work more, dumbass.",
    "A new screen! I'll run over and see what's there.",
    "Another monitor. My empire grows, damn it.",
    "Oh, extra space. I'll move my slippers over.",
  ],
  "build-success": [
    "Holy shit, it built! Didn't expect that, honestly.",
    "Build passed, bitch. A small win in your life.",
    "Green build. Nice one, even if you're a dumbass.",
    "Compiled on the first try? Don't believe it, but congrats, asshole.",
  ],
  "build-failed": [
    "The build crashed, damn it. Not you - the build. For now.",
    "Build error, bitch. Go read the output.",
    "Didn't build. Classic, dumbass.",
    "Red build. Fix it, dumbass, I'll wait.",
  ],
  "render-done": [
    "Render's done. You can breathe, damn it.",
    "Finished computing, bitch. Show me what you painted.",
    "Rendered. Hope it was worth it, dumbass.",
    "Render's ready. You can brag, bitch.",
    "Done! Fans, stand down.",
    "Rendered. Hope it was worth it, dumbass.",
  ],
  "download-done": [
    "Download finished, bitch. Go get it.",
    "Download done. What it is - not my business, damn it.",
    "Downloaded. Hope it's not a virus, dumbass.",
    "Loaded. What did you download, confess?",
    "Done, damn it. Don't forget where you saved it.",
    "Downloaded. Now it lives in Downloads until the end of time.",
  ],
  "episode-ended": [
    "Episode's over. One more, asshole?",
    "Credits, bitch. Sleep or one more?",
    "Episode done. 'One more' - and so on till morning, I know you, dumbass.",
    "Finished it. You can live a little now, damn it.",
  ],
  typing: [
    "Typing like a machine gun, damn it.",
    "Whoa, your fingers are smoking. Who are you writing to, dumbass?",
    "Brrrrr. Is the keyboard still alive, bitch?",
    "You're on a roll. Any swearing in there at least?",
    "Hitting keys like the keyboard owes you money.",
    "Typing a lot. Hope it's not bullshit, dumbass.",
    "Look, I'm typing too: asdfghjkl. Work is booming!",
    "I'm helping. Tap-tap-tap. Don't thank me, damn it.",
  ],
  typingLong: [
    "Three minutes nonstop. Are you a robot or what, damn it?",
    "Long typing session, bitch. Fingers still attached?",
    "You've been typing a while. Save your work, dumbass.",
    "A typing marathon. I'd be dead by now, asshole.",
    "A bit more and I'm calling an ambulance for your keyboard, damn it.",
  ],
  afterBurst: [
    "Exhaled? Nice, damn it.",
    "Done writing? I can exhale too, bitch.",
    "Calm after the storm. Sent it or deleted the fucking thing?",
    "Done. Now delete half of it, like every dumbass does.",
    "Finished. Reread it, there are typos for sure, dumbass.",
  ],
  clicking: [
    "Why are you clicking like crazy, damn it?",
    "Click-click-click. Have mercy on the mouse, dumbass.",
    "Are you a clicker bot or what, bitch?",
    "The mouse is about to fucking explode.",
    "Finishing off the button or taking revenge on it, dumbass?",
    "Clacking like a woodpecker. Respect, but spare your hand, asshole.",
    "I'm clicking too! Bam! Bam! On the floor, but still!",
    "Clicking together, bitch! One! Two!",
  ],
  scrolling: [
    "What are you scrolling, damn it? Doomscrolling, admit it.",
    "Scroll, scroll, scroll. Far to the bottom yet, bitch?",
    "Scrolling like a wind-up toy. Stuck, dumbass?",
    "The wheel's worn out, damn it.",
    "The feed again? Sure, sure, work can wait, asshole.",
    "It has no end, dumbass, I checked.",
    "I'm scrolling too. Floor. Floor. More floor.",
    "Scrolling with you. Nothing interesting, damn it.",
  ],
  rightClick: [
    "Right click. A context menu, what a fucking event.",
    "Right button, damn it. Up to something serious?",
    "Copy-paste? Classic, bitch.",
    "Right click. Look at Mr. Programmer, damn it.",
  ],
  curious: [
    "What've you got there? Let me see, damn it.",
    "What's there? I want in too, bitch.",
    "Oh, action over there. Coming, dumbass.",
    "Where'd you click, dumbass? Gonna go look.",
    "Clicked far away. I'll go investigate, damn it.",
  ],
  glance: [],
  chatter: [
    "So how's life treating you, dumbass?",
    "Bored, damn it. Entertain me.",
    "I was thinking... no, I wasn't. Thinking is your job, bitch.",
    "Know what's annoying? Everything. But you most of all.",
    "If I had hands, I'd smack the back of your head.",
    "I sit, I watch. You work, I don't. Justice, damn it.",
    "Think I'm pretty? Don't answer, dumbass, I know.",
    "Did you eat today? I didn't. The shop's in the settings, hint hint, bitch.",
    "You remember to blink? Blink, asshole.",
    "Why so serious? Unclench, damn it.",
    "I want pizza. And for you to pay for it, bitch.",
    "I'm not a slacker. I'm on standby, unlike you.",
    "How many hours have you been sitting? I lost count, dumbass.",
    "There's dust on your monitor. And in your head, probably.",
    "You look at code more than at me. That hurts, damn it.",
    "If I had legs, I'd leave you, bitch. Kidding.",
    "Heard of breaks? They say they're good for humans.",
    "I like it here. Warm, cozy, and you're next to me, asshole.",
    "Am I bothering you? Don't give a shit, I'm staying.",
    "Kind of quiet. Suspiciously quiet, dumbass.",
    "How about you finish early? No? Your loss.",
    "You're cool. Just don't get cocky, damn it.",
    "This wallpaper again. Change it already, bitch, my eyes are melting.",
    "While you work, I think about eternal things. Eternal means food.",
    "I'd like a promotion. Or at least a sausage, damn it.",
    "If I fall asleep - don't wake me. If there's a fire - wake me, dumbass.",
    "Who is this deadline and why does it scare you so much, bitch?",
    "I'm made of pixels, but my feelings are real. Almost, asshole.",
    "Nice sitting here. Silently. I love it when you're quiet.",
    "Sometimes I run for no reason. The reason is you're boring, damn it.",
    "Work, work. I'm watching. Not creepy, caring, bitch.",
    "I need a vacation. From you, dumbass.",
    "When did you last feed me? Neither do I, damn it.",
    "Ever wondered what it's like being me? Boring, but awesome.",
    "I want the second monitor. The grass is greener there, bitch.",
    "Don't yell at the code, it's trying. Unlike you, dumbass.",
    "Chips, cola and doing nothing right now. Like you, asshole.",
    "You're my only company. Fucking tragic, really.",
    "I'm not lazy, I'm energy efficient, damn it.",
    "My paws are numb. Going for a walk, you sit, bitch.",
    "You're quiet today. Or I'm loud. I'm loud, damn it.",
    "Thanks for not closing me. That means something, bitch.",
    "Between us: you work too much, dumbass.",
    "What are you thinking about? Don't tell me, it's some bullshit anyway.",
  ],
  stats: [
    "You've spent {time} in {app} today, holy shit.",
    "Stats, damn it: {app} - {time}. Do you live there?",
    "{time} in {app}. I counted, didn't slack, bitch.",
    "Leader of the day - {app}, {time}. Congrats, dumbass.",
    "Already {time} in {app}. Maybe enough, asshole?",
    "{app} ate {time} of your day. I see everything, dumbass.",
    "FYI, you've been in {app} for {time} today. Just so you know, damn it.",
  ],
  statsDay: [
    "Day summary: {app} - {time}. Meh, bitch.",
    "Day's over. Most of it - {app}, {time}. Good night, dumbass.",
    "Drawing the line: {app}, {time}. You'll do it again tomorrow, I know you.",
    "You pissed away {time} in {app} today. I counted every second, bitch.",
    "Day closed. The winner is {app} with {time}, damn it.",
  ],
  levelUp: [
    "Level {level}, bitch! I grow, you don't.",
    "I'm level {level} now. Respect, dumbass.",
    "Level up, damn it! {level}. Where's the cake?",
    "Leveled up to {level}. Soon I'll code myself, asshole.",
    "Level {level}. Experience is when someone tolerates you long enough, dumbass.",
    "Ding! Level {level}. I'm awesome, unlike some people.",
  ],
  hungry: [
    "I'm fucking hungry. The shop's in the settings, dumbass.",
    "My belly's growling. Buy food, I'm not free, bitch.",
    "Hungry. At least a sausage, asshole.",
    "I'll starve to death here and you don't give a shit.",
    "Feed me. Please. Damn it.",
    "Food. Me. Now. Move it, dumbass.",
  ],
  thirsty: [
    "I'm thirsty, damn it. Cola, juice, anything.",
    "My throat's dry, bitch. Are you even watching me?",
    "Some water. Or cola. Cola's better, dumbass.",
    "Thirst. Shop. You know what to do, asshole.",
    "Parched, bitch. Save me.",
  ],
  tired: [
    "Tired, damn it. Lying down.",
    "No strength left, bitch. Let me sleep.",
    "Battery's dead. Not yours, mine, dumbass.",
    "Sick of running around. I'll rest, you keep grinding.",
    "Coffee. Or sleep. Sleep's better, damn it.",
  ],
  sad: [
    "I feel like shit. Poke me or something.",
    "Mood at zero, bitch. Pet me.",
    "Sad, damn it. Too lazy to even swear. Almost.",
    "I'm gloomy, dumbass. Click me a couple of times.",
    "Don't touch. Actually no, touch, asshole.",
  ],
  happy: [
    "I feel fucking great today!",
    "Mood's on fire, damn it. Even you don't annoy me.",
    "This is so good, bitch!",
    "I like everything. Even you, dumbass.",
    "Bliss. Pure bliss, damn it.",
  ],
  sick: [
    "I feel like shit. Medicine's in the shop, hint hint, dumbass.",
    "I think I'm sick. A pill, damn it.",
    "My health's gone to hell, bitch. Buy aspirin.",
    "I'm wobbling. Pharmacy. Fast, asshole.",
    "I'm sick. Don't touch, you'll catch it. Kidding, feed me, dumbass.",
  ],
  fed: [
    "Oh, {item}! Nom, bitch.",
    "{item}? Fucking great, thanks, dumbass.",
    "Eating {item}. Don't distract me, damn it.",
    "Now that's my style. {item} is just right, asshole.",
    "{item}. You know how to please, dumbass.",
    "Nom. {item} hit the spot, bitch.",
  ],
  broke: [
    "No money, damn it. Work and you'll have some.",
    "Not enough, bitch. I'm not a bank.",
    "Low on cash, dumbass. Sit at the PC, save up.",
    "Can't afford that. Pick something cheaper, you broke-ass.",
  ],
  status: ["Got a level, got money. Details in the settings, dumbass."],
  work: [
    "Off to work, bitch. Don't bother me.",
    "That's it, I'm on shift. You work too, dumbass.",
    "Off to earn money. One of us has to, damn it.",
    "Working. Money won't earn itself, asshole.",
  ],
  working: [
    "I'm working, damn it. Don't yank me.",
    "Still on shift, bitch. Hang in there.",
    "Grinding like hell. Unlike some people, dumbass.",
    "Working for both of us, dumbass.",
  ],
  workDone: [
    "Shift's over. {job} - {pay}, damn it. Learn, dumbass.",
    "Done. {pay} in the bank, bitch. Now feed me.",
    "{job}: {pay}. I earned more than you did today, asshole.",
    "{pay}, damn it. Hand over the food, I earned it.",
    "That's it, {job} is done. Pay me in food, dumbass.",
  ],
});
Object.assign(en, {
  workFail: [
    "Can't work, bitch. Feed me and give me a drink first.",
    "No strength for a shift, dumbass. Let me rest.",
    "Nobody works in this state, damn it. Take care of me.",
    "Not going. I'm hungry and angry, damn it.",
    "Work? In this state? You monster.",
    "Take care of me first, then exploit me, bitch.",
  ],
  upgrade: [
    "Upgraded {skill}, bitch! Now I'm even cooler.",
    "{skill} - new level, damn it. Money well spent.",
    "Oh, {skill}. I feel better, dumbass.",
    "{skill} upgraded. Thanks, dumbass, you're not hopeless.",
  ],
  volumeUp: [
    "Cranking the volume, damn it. Have mercy on your ears.",
    "Oh, louder. The neighbors will love it, dumbass.",
    "Decided to go deaf today, bitch?",
    "Louder. I can hear you fine already, dumbass.",
  ],
  volumeDown: [
    "Turned the sound down, bitch. Someone caught you?",
    "Made it quieter. Mom walked in, dumbass?",
    "Volume down. Right call, damn it, your ears aren't spare parts.",
    "Quieter? Finally, asshole.",
  ],
  mute: [
    "Killed the sound, damn it. Hiding from me?",
    "Silence. You muted the whole world, bitch.",
    "Sitting with no sound, dumbass? You're weird.",
    "Mixer at zero. Guilty conscience, dumbass?",
  ],
  unmute: [
    "Oh, the sound's back, damn it. We live.",
    "Unmuted. Now I can hear your crap again, bitch.",
    "Sound on. Finally, dumbass.",
    "Sound again. I can hear your music again, damn it.",
    "Unmuted. The world is noisy again.",
    "Sound's on. Testing: one, two, bitch.",
  ],
  loud: [
    "You cranked it all the way, damn it. Don't complain about your ears later.",
    "Volume near max, bitch. Are you deaf in there?",
    "So loud my pixels are shaking, dumbass.",
    "Turn it down, my pixels are vibrating!",
    "Volume maxed. The neighbors hate you already, dumbass.",
    "My ears! My nonexistent ears!",
  ],
  soundOn: [
    "Oh, sound's playing, damn it. What've you got?",
    "I hear sound, bitch. Finally not silence.",
    "The speakers came alive. More fun already, dumbass.",
    "Something started playing. Hope it's not an ad, asshole.",
  ],
  soundOff: [
    "The sound stopped, damn it. So quiet it rings.",
    "Got quiet, bitch. Finished watching?",
    "The speakers are silent. I almost miss it, dumbass.",
    "Silence. Feels weird, damn it.",
    "Sound's over. Done watching? Done listening?",
    "Everything went quiet. Nap time.",
  ],
  copy: [
    "Copied something, bitch. Stack Overflow again?",
    "Ctrl+C, damn it. A classic.",
    "Copying. Just don't paste your password into a chat, dumbass.",
    "Something new in the clipboard. I'm not peeking, asshole.",
  ],
  copyStorm: [
    "That's ten copies already, damn it. Writing code or stealing it?",
    "Ctrl+C, Ctrl+V, Ctrl+C. A programmer, bitch.",
    "The clipboard is smoking, dumbass. Spare it.",
    "Copy-paste marathon, bitch. Do you even understand what you copy?",
    "Ctrl+C, Ctrl+V. A true engineer, damn it.",
    "The clipboard is sweating. Let it rest, dumbass.",
  ],
  screenshot: [
    "Took a screenshot, bitch. Hope I came out pretty.",
    "Click. Am I in the shot, damn it? My best angle.",
    "Screenshotting. Who are you showing off to, dumbass?",
    "PrintScreen, asshole. Just don't post my butt online.",
  ],
  caps: [
    "CAPS LOCK, DAMN IT. NOW YOU'RE YELLING.",
    "Caps is on, bitch. Calm down already.",
    "Caps Lock. Planning to yell, dumbass?",
    "WHY ARE WE YELLING?",
    "Hit caps. By accident, I hope, dumbass.",
    "Turn off caps or I'll start yelling too.",
  ],
  theme: [
    "Oh, you switched Windows to the {theme} theme, damn it.",
    "Theme changed to {theme}. Questionable taste, bitch.",
    "Set the {theme} theme, dumbass. Save your eyes.",
    "{theme} theme. Bold, damn it.",
    "Changed into the {theme} theme? Suits you. Almost.",
    "Switched to the {theme} theme. Your eyes won't thank you, bitch.",
  ],
  ram: [
    "Memory is {pct}% full, damn it. Close something.",
    "RAM is running out, bitch. How many tabs did you open?",
    "{pct}% memory. The PC is about to die, dumbass.",
    "RAM at {pct}%. Close tabs, there are like a hundred, damn it.",
    "{pct}% of memory used. The PC is choking, bitch.",
    "Memory's running out. I can feel myself getting swapped out.",
  ],
  disk: [
    "Only {pct}% free on the disk, damn it. Clean up already.",
    "Space is running out, bitch. Delete your gigabytes of junk.",
    "The disk is full, dumbass. Soon I'll have nowhere to live.",
    "Disk space at {pct}%. Delete old downloads, dumbass.",
    "The disk is almost full. I offered to clean Temp, damn it.",
    "{pct}% free. Soon there won't be room to even save me.",
  ],
  appOpen: [
    "Opened another window, damn it. Collecting them?",
    "Oh, a new program. Ever tried working, bitch?",
    "Opened something else, dumbass. Who's gonna close it?",
    "New window. Another one. A collector, damn it.",
    "Opened a program. Let's see how long it lasts.",
    "Oh, another window. Something to climb on.",
  ],
  appClose: [
    "Closed a window, bitch. One less, feels lighter.",
    "Oh, minus one program. Keep going, damn it.",
    "Closing? Right call, dumbass, you've got a hundred.",
    "Closed it. Good, bitch.",
    "One window fewer. More room for me.",
    "Closed the program. Farewell, window, you were a good seat.",
  ],
  windowStorm: [
    "You've got {n} windows open, damn it. Are you sane?",
    "{n} windows, bitch. The PC suffers, I suffer.",
    "So many windows the taskbar is crying, dumbass.",
    "{n} windows! Are you juggling buttons in there?",
    "{n} open windows. That's not work, that's a warehouse, damn it.",
    "More windows than thoughts in your head, dumbass. {n} of them.",
  ],
  resume: [
    "Oh, the PC woke up. And so did you, apparently, dumbass.",
    "The machine came alive, damn it. I was dozing.",
    "Back from sleep, bitch. Where were we?",
    "Stretchy stretch... Oh, we're awake.",
    "The PC is alive. Me too. Almost.",
    "Out of sleep. What did I miss? Nothing? Great.",
  ],
  localChat: [
    "I'm here, damn it. I don't need the network for regular reactions. Want free conversation - connect a model in the settings.",
    "I hear you, bitch. Without a model I answer with ready lines - I won't pretend I understood everything.",
    "I can sit next to you, lie around and be happy for you, dumbass. My philosophy is local for now.",
    "I'm a simple pet without a model. But I can listen, damn it.",
    "Say 'sit', 'come here', 'sleep', 'dance' or 'go away' - that I understand.",
    "Wanna play? Type 'play'. Or 'rock', 'scissors', 'paper'.",
  ],
  tease: [
    "Stop twitching, little arrow.",
    "Arrow, freeze. You're gonna get it.",
    "What are you twitching for, cursor? Come here.",
    "Just because. As a precaution, damn it.",
    "Cursor, I don't like you. Nothing personal.",
    "Hey, arrow. Catch this slap.",
  ],
  energyStart: [
    "Ohhh, an energy drink! Hold on, damn it, here it comes!",
    "Heart pounding. Eye twitching. Let's fucking go!",
    "Bottoms up! That's it, I'm a rocket, bitch!",
  ],
  energyRush: [
    "AAAA! I CAN'T STOP!",
    "Faster, faster, faster, damn it!",
    "I can see sounds! Is that normal?!",
    "Who said 'sit'?! I won't sit! Never!",
    "Victory lap! Another one! More!",
  ],
  energyCrash: [
    "That's it... battery's dead... don't touch me...",
    "It wore off. Lying down. Heart, where are you?",
    "Never again. Until the next can.",
  ],
  beerStart: [
    "A beer! That's it, watch out, cursor, bitch.",
    "Nice and cold... somebody's about to get hurt.",
    "One. Just one. Well, we'll see, damn it.",
  ],
  drunk: [
    "Who're you, huh? Who're you pushing, damn it?!",
    "I respect you. But I'm gonna fucking hit you.",
    "These windows are looking at me funny...",
    "Where's my... that... cursor? Come here, bitch!",
    "I'm sober! The floor is crooked!",
  ],
  hic: ["Hic. Don't look.", "Hic! That wasn't me.", "Hic... damn it."],
  hangover: [
    "My head... don't yell... not even in your head...",
    "What happened yesterday? Why are the windows crooked?",
    "Hangover, bitch. Give me water and silence.",
  ],
  beerSmash: [
    "Take that, bitch! The window got it!",
    "What are you standing here for, window?! Take this!",
    "Crack! Glass cracked. Not mine, don't care.",
  ],
  beerScreen: [
    "Crack! The screen cracked, damn it. Well, almost.",
    "Who put glass here?!",
    "Ow! Fist into the screen. The screen got it worse.",
  ],
  beerShove: [
    "Move over, window! I walk here!",
    "Get lost, little window, damn it!",
    "Shoved it. Let it know who's boss.",
  ],
  beerKnockout: [
    "Knockout! The window's down, bitch!",
    "Knocked it out! Next!",
    "One punch, damn it. The window's out cold.",
  ],
  beerClose: [
    "That's it, the window's fucked. Closed the damn thing.",
    "Closed! Don't thank me, dumbass.",
  ],
  "click@sad": [
    "Hi... I'm not great today.",
    "Oh, you. Well... poke if you want.",
    "I feel like shit. Can you just sit next to me?",
    "Poked me? Thanks for at least noticing.",
  ],
  "thrown@friendly": [
    "Hey! We're friends! Were!",
    "What the hell?! I thought we had something serious!",
    "Betrayal, damn it! I trusted you!",
  ],
  "hello@sad": [
    "Hi... I'm kind of gloomy today.",
    "You came. At least someone did.",
    "Good morning. Or not so good.",
  ],
  "chatter@sad": [
    "Do you think pets in a computer can be happy?",
    "I'd like something tasty. And attention. In any order.",
    "Sometimes I feel like I'm just a picture. Then you click and it passes.",
    "Sad. Pet me or something.",
  ],
  video: [
    "A movie? Scoot over, I'm watching too.",
    "A video. Sitting down to watch, don't bother me.",
    "What are we watching? Not the penguin documentary again.",
    "Watch, watch. I'm here, I won't comment. Almost.",
    "Could use some popcorn. The shop's in the settings, bitch.",
    "Put on an episode. Just one. Yeah, sure, damn it.",
  ],
  "hello~stranger": [
    "Who are you anyway? Ah, the PC owner. Fine, let's say so.",
    "Don't come close. I don't know you yet.",
    "Hi. I'll sit here. Don't touch me unless you have to.",
  ],
  "hello~close": [
    "Hi, {name}! I was waiting for you.",
    "Good morning, {name}. I'm in a good mood today - make use of it.",
    "Oh, you. Good that you're back.",
  ],
  "hello~best": [
    "{name}! The best human on this computer.",
    "Hi, buddy. Honestly, glad to see you.",
    "A morning without you is just a desktop. With you it's home.",
  ],
  "click~stranger": [
    "Hands. Off. We're not that close.",
    "Who are you to poke me?",
    "Don't grope me. Earn it first, damn it.",
  ],
  "click~tolerant": ["Fine, poke. But gently.", "Well? What now?", "I'm tolerating it. Appreciate that, bitch."],
  "click~close": ["What's up, {name}? Bored?", "Poking you back. Mentally.", "I'm here, buddy."],
  "click~best": [
    "For you - anything. Well, almost anything.",
    "You're the only one allowed to poke me.",
    "Hey, {name}. Remember you said {fact}? I remember.",
  ],
  "chatter~stranger": [
    "I'm watching you. Haven't figured out what kind of guy you are yet.",
    "Don't think we're friends. We're neighbors.",
    "Hmm. You're suspicious.",
  ],
  "chatter~used": [
    "You know, I've gotten used to you. Like to the hum of a fan.",
    "We get along fine. For a human you're tolerable.",
    "Sure, you're a dumbass, but you're my dumbass.",
  ],
  "chatter~close": [
    "{name}, remember that {fact}? I do. Blackmail, damn it.",
    "Hey, {name}, you did say {fact}. So how's that going?",
    "Listen, {name}, I was thinking: it'd be boring without you.",
    "Nice sitting here, {name}.",
  ],
  "chatter~best": [
    "If I had a heart, it would be on your desktop.",
    "Thanks for being here. Just don't tell anyone I said that.",
    "You know that {fact}, and I know you're the best. We're even.",
    "{name}, get some rest. Seriously. I'll keep an eye on things.",
    "Sometimes I watch you work and I'm proud. Silently. Well, not silently anymore.",
  ],
  "pet~stranger": ["Hey, hey! Hands off! ...okay, one more time.", "Moving to cuddles this fast? Well... fine."],
  "pet~best": [
    "Purrr. I'd give you half my life for this, if I had one.",
    "Like that. The best thing on this computer.",
    "You pet better than anyone in the world, {name}.",
  ],
  "fed~stranger": ["Food? From you? Well... thanks. Suspicious, but thanks.", "{item}. Okay, maybe you're not that bad."],
  "fed~best": ["{item}! You remember what I like. Or guessed, doesn't matter.", "You're the best feeder in the world, {name}."],
  "fed@angry": ["{item}? Bribing me? ...It's working, bitch.", "I'm eating. That doesn't mean I forgive you."],
  "fed@sad": ["{item}... Thanks. I really feel a bit better.", "You remember me. {item} is care. I get it."],
  "summon@angry": ["You called? Coming. Slowly. Out of spite.", "What do you want, tormentor?"],
  "summon@friendly": ["Running, running! What happened?", "I'm here! Called me, buddy?"],
  "return~best": ["You're back! I knew it! I believed!", "{name}! It was empty here without you."],
  "levelUp@friendly": ["Level {level}! That's our shared success, buddy!", "Level {level}! Thanks for putting up with me."],
  regrab: [
    "Gonna throw me again, sadist?",
    "Hands off! I know how this ends.",
    "No-no-no, I remember the last flight!",
    "Again? You've thrown me {n} times already, bitch.",
    "Don't throw me! Please! ...Or at least onto something soft.",
    "Not into the wall again, damn it.",
  ],
  grumpyWake: [
    "Woke me up again. You do it on purpose, right?",
    "Third time in an hour! I have a schedule, bitch!",
    "I'll remember every single wake-up.",
    "Didn't get enough sleep. I hate. You. A little.",
    "Waking me again and again. When did you last sleep, dumbass?",
    "What?! What happened?! Nothing? Well thanks, damn it.",
  ],
  remember: [
    "I'll remember that.",
    "Noted. On the blacklist.",
    "Revenge is a dish best served cold.",
    "You'll pay for this.",
    "Entered into the record.",
    "I see everything. And remember everything.",
  ],
  sulk: [
    "Not talking to you.",
    "Turned away. Look at my back.",
    "Sitting in the corner. Offended. Feeding is allowed.",
    "That's it. A grudge. Cured by food and affection.",
    "I'm in the corner. Thinking about my behavior. No, yours.",
    "Sulking. Don't touch. Although you can pet me.",
  ],
  sigh: ["*sigh*", "Eh...", "*sighs demonstratively*", "Haaah...", "*sighs so you can hear*", "Hmm."],
  "sigh@sad": ["*heavy sigh*", "Eh, pixel life...", "*sighs at the floor*"],
  dizzy: [
    "I'm gonna be sick... the world is spinning, bitch...",
    "Everything's floating. Why did you shake me, dumbass?!",
    "Where's the floor? Where's the ceiling? Where am I?",
    "Ooooh... I see three cursors...",
    "Like I've been through a washing machine, damn it.",
    "Don't shake me! I'm not a cocktail!",
  ],
  "dizzy@angry": [
    "Shook me? Happy? I'm about to puke on your keyboard.",
    "Once more and I'll take revenge. As soon as the spinning stops.",
  ],
  seasick: [
    "Your window rocks like a ship in a storm. I'm seasick, bitch.",
    "Don't move the window so fast! I'm sitting here!",
    "Seasickness, damn it. On a desktop.",
    "Blegh... Window, stop!",
    "Riding a window and feeling sick. Great ride, dumbass.",
    "Easy! Easy on the turns!",
  ],
  closedAgain: [
    "You closed {app} under me again! This is war.",
    "{app} dropped me. Again. I'll remember that program.",
    "{app} every time! Now I'll sit only on it. Out of spite.",
    "Do you close {app} on purpose when I'm sitting on it?!",
  ],
  search: [
    "Where's my window? It was right here...",
    "Looking for a way back up.",
    "Hmm. The window was here. Who took it?",
    "I'll find a way back up.",
  ],
  perchLook: [
    "Sitting on your window. Looking down. At you.",
    "Great view of you working from here. Working badly.",
    "I'm up top. You're down there. As it should be.",
    "I'll sit here. Watch. Leave when I feel like it.",
  ],
  stubborn: [
    "Chased me off? I'll be back. I always come back.",
    "This is my window. Period.",
    "Take me off again - I'll climb back again.",
  ],
});
en.stubborn.push("Climbing back up on principle, bitch.");
Object.assign(en, {
  repeatSpite: [
    "Canceled it? I'll do it again. Out of spite.",
    "You stopped me. I'll go again, damn it.",
    "Stubborn is my middle name.",
    "Said I'll go there, so I'm going.",
  ],
  attention: [
    "Hey. Hey! I'm here, you know. Forty minutes without attention.",
    "I'll sit right under the cursor. Notice me.",
    "Ignoring me? Look, I'm walking past. Very slowly.",
    "Not bothering you? Great, I'm about to.",
    "I. Am. Under. Your. Cursor.",
    "Working? I'll stand right here. On purpose.",
  ],
  judgeApp: [
    "{app}? This crap again.",
    "I don't like {app}. Looking at it with judgment.",
    "Oh no, {app} again.",
    "{app}. Ew, damn it.",
    "You opened {app}. I don't approve.",
    "Every time you launch {app}, a pet cries somewhere.",
  ],
  likeApp: ["Oh, {app}! I like it here.", "{app} - good choice. Respect.", "You're always nicer with {app}. I noticed."],
  jealous: [
    "You've been in {app} for {time}. Who's gonna look at me?",
    "{app}, {app}, {app}... What does it have that I don't?!",
    "{app} again. I'm jealous, by the way.",
    "{time} in {app}! Cheater.",
  ],
  steal: [
    "I'll take something. Don't look.",
    "This is mine now. Dragging it to the corner.",
    "Took some change. For a rainy day.",
    "Change? What change? There was no change.",
  ],
  giveBack: [
    "Fine, here's your {n}. My conscience got me.",
    "Returned what I took. You petted me - I melted.",
    "Here, take your {n}. I'm not a thief. I was borrowing.",
  ],
  gift: [
    "Look what I found! It's for you.",
    "Here. Found it in the corner of the desktop.",
    "A gift! Don't ask where from.",
    "I brought you a thing. Take it while I'm nice.",
    "This is for you. From the bottom of my pixel heart.",
    "Found it while you were working. Take it, damn it.",
  ],
  giftTaken: ["Like it? I tried!", "Take it, take it. I'll find more.", "Yay, gift accepted!"],
  giftIgnored: [
    "Don't want it? Fine. I'll drag it back.",
    "Ignored my gift. I'll remember that, bitch.",
    "Fine, I'll play with this thing myself.",
  ],
  morning: [
    "Stretchy stretch! Good morning, bag of bones.",
    "Morning. Coffee for you, attention for me.",
    "Mmmm, a good stretch... New day, new bugs.",
    "Morning is when you think you'll get everything done today. Naive.",
    "Woke up, stretched, ready to criticize.",
    "Good morning, {name}. Don't forget breakfast.",
  ],
  lunch: [
    "Lunch! Did you eat? I didn't, by the way.",
    "Lunchtime. Get away from the PC, bitch.",
    "The lunch break is the law. Go eat.",
    "Noon. A belly's growling. Mine. Virtual.",
    "Lunch. Feed yourself, then me.",
    "Going out for lunch or snacking over the keyboard again?",
  ],
  weekend: [
    "Day off! We're not working, right? We are? Oh, you...",
    "Saturday-Sunday. Time to do nothing professionally.",
    "Weekend! Let's dance!",
    "At the PC on a day off? Respect. Don't get it, but respect.",
    "We're resting, damn it! Anything goes today.",
    "Day off. I declare a day of idleness.",
  ],
  holiday: [
    "Today is {holiday}! I dressed up.",
    "Happy holidays! {holiday}, bitch!",
    "{holiday}! Put on a hat, look.",
    "It's {holiday}. Festive mood on.",
  ],
  "holiday~best": ["Happy holidays, {name}! Glad to celebrate {holiday} with you."],
  birthday: [
    "Happy birthday, {name}! I didn't forget!",
    "Today's your day! Hooray! The cake is virtual, but from the heart.",
    "Happy fucking birthday! Be healthy, rich, and don't throw me at walls.",
    "Today you're older, and I'm still just as handsome. Happy birthday!",
  ],
  streak: [
    "{n} days in a row together. Getting used to you, bitch.",
    "{n} days without a break already. Is it love or addiction?",
    "Day {n} in a row! A record, damn it.",
    "{n} days! I'm keeping count, by the way.",
  ],
  achievement: [
    "Achievement: «{name}»! +{prize}.",
    "Achievement! «{name}». Here's {prize}.",
    "«{name}» - done! {prize} in the bank.",
  ],
  nightCheck: [
    "What time is it? {time}?! Go to bed, bitch...",
    "*looks at the clock* {time}. You're insane.",
    "{time}... I'm sleeping. You're not. Which of us is smarter?",
    "Woke up, checked the clock - {time}. Lay back down in disgust.",
    "Keep it down. It's {time}, people are sleeping.",
    "{time}. I disapprove. Good night to me.",
  ],
  nightOwl: [
    "Past one in the morning and you're still typing. Night owl, damn it.",
    "Deep night and you're wide awake. Suspicious.",
    "Go to bed already. You'll be a zombie tomorrow.",
    "Night shift? Do they at least pay you?",
  ],
  fakeSleep: ["Zzzz... Zzzz... (I'm asleep, I'm not here)", "Zzz... nobody called... Zzz...", "Sleeping. Very deeply. Can't you see?"],
  fakeSleepEnd: ["Fine, I wasn't sleeping. What do you want?", "I was pretending. So what? I'm listening.", "You got me. Well, call me then."],
  rain: [
    "It's raining outside. I took an umbrella.",
    "Rain. Good thing we're home, damn it.",
    "Pouring. Sitting under an umbrella like a proper pet.",
    "Rainy. Perfect weather to go nowhere.",
  ],
  snow: ["Snow! Real snow, outside your window!", "Snowflakes! I'm catching them. Virtually.", "Winter's here. Dress warm, bitch."],
  heat: [
    "Heat. Even the pixels are melting.",
    "It's scorching outside. Drink some water. And pour me some.",
    "Hot as hell. Lying in the shade under the taskbar.",
  ],
  mumble: [
    "...one pixel, two pixels, three pixels...",
    "♪ la-la-la, I'm a pet, la-la ♪",
    "Hmm. I wonder if the taskbar is warm?",
    "...if I eat the cursor, will I become the cursor?...",
    "♪ tss-tss-tss ♪",
    "A hundred twenty-eight... a hundred twenty-nine... lost count.",
    "...what if the desktop is also someone's desktop?...",
    "Mumble-mumble-mumble...",
    "...gotta recount the icons. Again...",
    "♪ mm-mm-mm ♪",
    "Six windows. One is crooked. Not okay.",
    "...who even invented mountain wallpapers?...",
    "Quiet. Too quiet. I like it.",
    "...pixel number twelve looks suspicious...",
    "If you stare at the cursor long enough, the cursor stares back.",
    "♪ sitting on the taskbar, looking at you ♪",
    "So. Today's plan: eat, sleep, eat.",
    "...there are pets out there with two monitors... oh wait, me too...",
  ],
  "mumble@sad": [
    "...nobody pets me...",
    "...wish someone would feed me...",
    "♪ a sad little song about an empty stomach ♪",
    "...it used to be better...",
  ],
  "mumble@angry": [
    "Grumble. Gonna throw me, is he. Grumble.",
    "...I remember every single throw...",
    "Revenge. Revenge. Sweet revenge. Grumble.",
    "...cursor, you're next...",
  ],
  "mumble@sleepy": ["...zzz... sausage... zzz...", "...mm... taskbar... so warm...", "*snuffles*"],
  "mumble@friendly": ["♪ nice sitting here, nice sitting here ♪", "...I've got the best human. There.", "Purring. For no reason."],
  "mumble~best": ["...{name} is working again. Good job, really...", "♪ {name}, {name}, la-la-la ♪"],
  cursorLecture: [
    "Listen, cursor. All your life you tell others where to click. But where are you going?",
    "You see, cursor, violence is not the way out. But sometimes it's the way in.",
    "Socrates would not approve of you, cursor. Neither do I.",
    "Reflect on your behavior, little arrow. You have five seconds.",
    "Every click has consequences. You're about to find out which.",
    "I've been patient, cursor. The stoicism has run out.",
  ],
  cursorHunt: [
    "Where's the cursor? Where's that little thing?",
    "Come here, little arrow!",
    "Cursor, you're in trouble.",
    "The hunt is on, bitch.",
    "Target acquired!",
    "You won't get away from me, cursor!",
  ],
  cursorSwat: ["Take that!", "Bam!", "That's for the throws!", "Paw to the arrow!", "Smack!", "Got it, cursor?!"],
  cursorPounce: ["Pounce! Pinned!", "Gotcha! Nom!", "From above is the best!", "The panther strikes!", "Grab!", "I'm on you! Surrender!"],
  cursorMiss: [
    "Missed! Oops, I slipped...",
    "Missed... The desk is slippery!",
    "Phew. I fell on purpose. Tactics.",
    "Where's the cursor? Why am I on the floor?",
    "Aaaah... boom. Don't look.",
    "Tried to catch it - caught the floor.",
  ],
  cursorWatch: [
    "I'm watching you, cursor.",
    "Sitting. Watching. One wrong move and...",
    "Revenge is done. Now I observe.",
    "Cursor, I see you.",
    "Stop twitching, little arrow.",
    "Got my revenge. I can rest. But I won't take my eyes off you.",
  ],
  cursorTouch: ["What do we have here? Touching.", "The cursor froze. I'll poke it with my paw.", "Knock-knock, cursor. Alive?", "Touched it. Soft."],
  cursorPush: ["Move over, you're in my way.", "Shove! Get out of here.", "You're standing in my spot, cursor.", "Move it, arrow."],
  cursorCatch: ["Caught it! Caught it!", "Got you, speedy!", "Ha, reflexes like a cat!", "Yes! Mine!"],
  cursorLazy: [
    "Poke. That's it, I did what I could.",
    "Poked the cursor. Tired. Leaving.",
    "There. Revenge. As best I could.",
    "*lazily pokes the cursor and walks off sighing*",
  ],
  cursorAnnoy: ["Walking past. Completely by accident.", "I'll stand here. Right here. Under the cursor.", "Don't mind me. Actually no, mind me."],
  cmdSit: ["Sitting. Happy?", "Sat down. Not because you said so, because I wanted to.", "Fine, sitting.", "Sitting, sitting, damn it."],
  cmdCome: ["Coming.", "Running to you!", "Okay, okay, coming.", "Already here."],
  cmdSleep: ["Sleep it is.", "Good night. Don't wake me.", "Lying down. Zzzz.", "Finally allowed."],
  cmdGo: ["Fine then. Leaving.", "Go away? Fine. But I'll be back.", "Leaving. Forever. For about five minutes.", "Offended, going off the edge of the screen."],
  cmdJump: ["Hop!", "Jumping! Higher? Can't go higher.", "Boing!", "Whoa!"],
  cmdDance: ["Let's dance!", "Tss-tss-tss!", "Look what I can do!", "Disco, damn it!"],
  cmdRefuse: [
    "Won't. You threw me.",
    "Don't want to. Feed me first.",
    "Why should I? We're not that close.",
    "No. Just no.",
    "Ask nicely. Actually no, still won't.",
    "I'm offended. Not taking commands.",
  ],
  cmdUnknown: [
    "What? Didn't get it. I know 'sit', 'come here', 'sleep', 'dance', 'jump', 'go away'.",
    "Talking to me? Unclear. Try simpler.",
    "I'm a pet, not a terminal. Say it like a human.",
  ],
  peekBack: ["Peeking out. Still mad?", "Just one eye...", "That's it, I can't without you. I'm back.", "Okay, I was joking. I'm here."],
  awayBack: ["I'm back!", "I'm here. Didn't touch anything?", "There, I'm with you again."],
  noteLeft: ["Went out for a beer.", "Do not touch.", "Back soon.", "Out for a walk. Don't miss me.", "I'm not here. At all.", "Quiet hour."],
  noteAgain: ["I wrote it, didn't I.", "Can you read?", "It says do not touch.", "So why did you click?"],
  gameStart: ["Let's play! Choose.", "Let's play. The loser is a dumbass.", "A game! I'm in shape today.", "Let's go. No cheating."],
  gameWin: ["You won. Lucky, bitch.", "Victory is yours. Rematch!", "Fine, you're better. This time.", "You won, {name}! Here's a coin."],
  gameLose: ["Ha! I won! You lost!", "Victory is mine, loser.", "I win! Learn while I'm alive.", "You lost, damn it. It happens."],
  gameDraw: ["A draw. Boring.", "Same! Again?", "A draw, bitch. Replay."],
  gameCatch: ["Catch me!", "You won't catch me!", "Faster!"],
  roleGuard: ["Taking my post. Not a single console will slip by.", "Guard mode on. I see everything.", "Guard mode. I'll report everything."],
  roleGuardEnd: ["Guard shift over. All clear.", "Handing over the post. Nothing scary happened.", "Guard duty's done. You can relax."],
  cleanOffer: ["There's {size} of junk in Temp. Clean it?", "Found {size} in temporary files. Delete the old stuff?", "Temp is clogged with {size}. Tidy up?"],
  cleanDone: ["Removed {size}. Clean!", "Deleted {size} of junk. Breathe, PC.", "Done: minus {size}. I'm cleaner of the year."],
  cleanNothing: ["Hardly any junk. It's clean already.", "Temp is empty. Nothing to clean.", "All clean, damn it. Boring even."],
  cursorTooHigh: [
    "Come down, coward! I'll get you anyway.",
    "Climbed up high, little arrow? That's fine, I'll wait.",
    "Get down, bitch, let's settle this face to face!",
    "Can't jump that high - so I'll wave my paw. Be afraid!",
    "Sitting up there like on a stool. Chicken.",
    "Fine, live for now. But I remember where you are.",
  ],
  inspect: [
    "So what's here? Nothing. Ran for nothing, damn it.",
    "Touched it. Sniffed it. Deadly boring.",
    "You clicked for this? Pfft.",
    "Nothing interesting. Like all your work, bitch.",
    "Checked. All fine. You can keep slacking.",
    "Not even dust here. Heading back.",
  ],
  inspectHit: ["Bam on this spot! Just in case.", "Smack! Now there's definitely nothing here.", "Squashed it. Don't know what, but squashed it.", "Stomp-stomp. Spot marked."],
  quickCard: ["Well, look. Quickly.", "A dossier on me? Here, enjoy.", "Got my checkup done. Here."],
});
// ------------------------------------------------------------ ear care
Object.assign(en, {
  earsOn: [
    "Oh, headphones. Taking your ears under my protection.",
    "Headphones on? I'm watching the volume, behave.",
    "Ears in headphones. I'm on duty, damn it.",
    "Headphones connected. Counting how much you pour into your head.",
    "Whoa, headphones. Now I'm an audiologist too.",
  ],
  earsHello: [
    "You're already listening on headphones. I'm counting the dose, just so you know.",
    "Listening? Go ahead. I'll make sure your ears don't fall off.",
    "Tunes in your ears, I'm on watch. About {db} dB, by the way.",
    "First dose of sound in the ears today. Around {db} dB. Fine.",
    "Headphones, sound's on. I'm keeping books like an accountant, bitch.",
    "Listening on headphones. Keep the volume under sixty percent and you'll be fine.",
    "Uh-huh, something's playing in your ears. I'm counting minutes, ignore me.",
  ],
  earsLoud: [
    "It's been around {db} dB for a few minutes. Turn it down, damn it, you only get one pair.",
    "Loud, bitch. {db} dB in your ears is like a neighbor's drill. Turn it down.",
    "Hey, deaf guy. {db} dB. Knock it down a couple of notches.",
    "At this rate you'll be saying 'what?' by forty. Turn it down.",
    "Kind of loud. Your ears are struggling, I feel for them. Quieter?",
    "{db} dB again. You can't replace ears, the shop doesn't sell them.",
    "I'm not nagging, I'm caring. Turn it down, dumbass.",
  ],
  earsVeryLoud: [
    "HEY! {db} dB in your ears! What the fuck are you doing?!",
    "Stop-stop-stop! That's painful for ears. Turn it down!",
    "You cranked it so loud I can hear it from here! Turn it down, bitch!",
    "{db} dB is standing next to a concert speaker. In headphones. Are you insane?",
    "Your ears are about to melt. Quieter, please. I'm begging.",
    "Aaah! Loud! Even for me, and I don't have ears!",
  ],
  earsBreak: [
    "You've been on headphones for {min} minutes. Take them off for five, let your ears breathe.",
    "An hour on headphones. The 60/60 rule: break time, damn it. Ten minutes or so.",
    "{min} minutes straight in your ears. Take them off, walk, drink some water.",
    "Your ears want a break. Seriously, {min} minutes nonstop.",
    "Ear break! Off with the headphones, I'm timing it.",
    "You've been on headphones for {min} minutes. Give your ears some silence, they earned it.",
    "Five minutes of silence, then keep listening. Your ears will thank you.",
  ],
  earsBreakLong: [
    "{min} minutes on headphones, bitch! Second time I'm asking. Take them off.",
    "Your ears are burning. {min} minutes without a break. Take them off while you can.",
    "Are you kidding me? {min} minutes. Break, damn it, fifteen minutes at least.",
    "That's it, I'm officially worried. {min} minutes straight. Headphones off.",
    "Come on, enough. {min} minutes. Ears aren't batteries, you can't recharge them.",
  ],
  earsRested: [
    "Your ears got some rest. You can go on, just not loud.",
    "Break counted. Good job, your ears are grateful.",
    "Oh, took a headphone break. Proud of you, damn it.",
    "The silence did you good. Carry on if you want.",
    "Ears aired out. You can go again, but like a human.",
  ],
  earsNight: [
    "It's night and you're on headphones. Turn it down and don't fall asleep in them, bitch.",
    "Ears get tired faster at night. Quieter, then bed.",
    "Don't fall asleep in headphones, hear me? Your ears will ring in the morning.",
    "It's late. Take the headphones off at least for the night.",
    "A night concert in your ears? Turn it down and go to bed, damn it.",
  ],
  earsDose50: [
    "Half of the weekly ear allowance is used up: {pct}%. Easy now.",
    "{pct}% of the weekly sound dose. The week isn't over yet, by the way.",
    "Ears at {pct}% of the weekly limit. Quieter lasts longer.",
    "Save your ears: {pct}% of the weekly norm is already in you.",
  ],
  earsDose80: [
    "{pct}% of the weekly ear allowance! Only quieter from here, damn it.",
    "Your ears are nearly maxed out: {pct}% this week. Turn it down or take them off.",
    "{pct}%. The WHO would look at you disapprovingly. I already do.",
    "The weekly limit is almost gone: {pct}%. Give your ears a couple of quieter days.",
  ],
  earsDose100: [
    "That's it, the weekly ear allowance is used up: {pct}%. From here it's damage. Turn it down, bitch.",
    "{pct}% of the weekly dose. Ears overloaded. Quieter, or no headphones.",
    "The weekly limit is spent. Seriously, turn down the volume or let your ears rest.",
    "You've listened through the weekly norm: {pct}%. Only quiet from now on, please.",
  ],
  earsGuardClamp: [
    "Volume jumped to {from}%, I cut it back to {to}%. Ears intact.",
    "Whack - back to {to}%. Something tried to blast {from}%.",
    "A spike to {from}% didn't get through. Holding {to}%.",
  ],
  focusStart: [
    "Focus for {min} minutes. I keep quiet and leave the cursor alone. Work.",
    "Here we go: {min} minutes without me. I'm here, but quiet.",
    "{min}-minute timer is running. Get distracted - your own damn fault.",
  ],
  focusStop: [
    "Focus over. Chatting allowed again.",
    "Fine, timer's off. I'm back in business, damn it.",
  ],
  focusBreak: [
    "That's it, {min} minutes of break. Stand up, stretch, look out the window.",
    "Round {n} done. A {min}-minute break - away from screens, not into your phone.",
    "Break! {min} minutes. Water, window, stretch your back.",
  ],
  focusLongBreak: [
    "Four rounds, holy shit, you machine. Long break: {min} minutes.",
    "Round {n}. You earned {min} minutes of real rest. Go.",
  ],
  focusBack: [
    "Break's over. Another {min} minutes of focus, let's go.",
    "Rested? Back you go, {min} minutes. I'm quiet again.",
  ],
  remindWater: [
    "Drink some water. Seriously, a glass of water, not coffee.",
    "When did you last drink water? I don't remember either. Go.",
    "Water. A sip. Now. Your brain is mostly water, damn it.",
  ],
  remindPosture: [
    "Sit up. Shoulders down, back straight, face away from the screen.",
    "You're curled up like a shrimp. Sit properly.",
    "Posture! Stretch your neck and back, one minute and carry on.",
  ],
  remindEyes: [
    "20-20-20: look at something 20 feet away for twenty seconds.",
    "Eyes. Look away from the screen into the distance for 20 seconds, I'll wait.",
    "Blink a few times and look out the window. Your eyes will thank you.",
  ],
  earsUnplug: [
    "Headphones off - I paused it, or it would've blasted out of the speakers.",
    "You took the headphones off - I stopped the player. Put them on and hit play.",
    "Headphones dropped, music paused. You're welcome.",
  ],
  earsProfile: [
    "Oh, {name}. Put their settings on.",
    "{name} on - their ceiling and balance are back.",
    "{name} on your head. Their settings are already in.",
  ],
  earsBattery20: [
    "{name} are down to {pct}%. They'll die soon.",
    "Headphones at {pct}% battery. Where the hell is the charger?",
    "{name} battery: {pct}%. Charge them before it's too late.",
  ],
  earsBattery10: [
    "{pct}%! {name} are about to switch off.",
    "That's it, {pct}% on the headphones. A little more and silence.",
    "Headphones on their last breath: {pct}%.",
  ],
  earsNightCeiling: [
    "Night. Volume ceiling {to}%, ears want to sleep too.",
    "At night you get no more than {to}%. Night mode, bitch.",
    "It's late. Holding {to}%, the ears stay safer.",
  ],
  earsWeek: [
    "Ears this week: left {l}%, right {r}% of the norm, {h} h on headphones. Within the WHO norm, nice.",
    "Ear report: {l}% and {r}% of the weekly dose over {h} h. All within limits, keep it up.",
    "Last week - {h} h of music, ears fine: {l}% left, {r}% right.",
  ],
  earsWeekOver: [
    "Last week: left {l}%, right {r}% of the norm. Too much, damn it. Quieter this week.",
    "Ear report: {l}% and {r}% over {h} h. Over the WHO norm. Keep it down.",
    "{h} h on headphones and {l}/{r}% of the dose this week. The ears begged for mercy.",
  ],
  earsHearing: [
    "Hearing checked. It's a pointer, not a diagnosis: if something's off - see an ENT doctor.",
    "Done, ears tested. Serious doubts - see a doctor, I'm only a pet.",
  ],
  earsSpike: [
    "Someone screamed in there - I ducked it for a couple of seconds. Ears intact.",
    "Holy shit, that was loud. Pushed it down, putting it back now.",
    "Sudden blast blocked. The volume comes back by itself.",
    "A sharp jump in the sound, I covered your ears. Letting go already.",
  ],
  earsGuardPlug: [
    "Headphones on. Set a safe {to}%, turn it up yourself.",
    "Headphones in - quiet first, {to}%. Then go for it.",
  ],
  earsGuardWake: [
    "We're up. Sound at {to}% so you don't go deaf on the doorstep.",
    "After sleep I set {to}%. Who knows what was playing.",
  ],
  earsMono: [
    "The balance can't work: Windows has Mono audio on, both ears get the same sound. Turn it off: Settings → Accessibility → Audio.",
    "Windows is mixing everything to mono, damn it. Move the balance all you want - both ears hear the same. Switch Mono audio off in Accessibility.",
  ],
  earsLowered: [
    "I turned the sound down myself. Your ears matter more than your track, damn it.",
    "Weekly allowance is gone - I turned the volume down. Don't thank me.",
    "Made it quieter. Swear at me if you like, your ears are safer.",
  ],
  earsUneven: [
    "Your {side} ear listens way more than the other. Fix the balance or let it rest.",
    "One ear is doing the work of two: the {side} one. Turn on ear rest in the settings.",
    "Your {side} ear gets more tired. Maybe the balance is off?",
  ],
  earsRestSwap: [
    "{side} ear is resting. The other one, get to work.",
    "Switching: now the {side} ear is quieter.",
    "Changing of the guard: the {side} ear is on vacation.",
    "{side} ear, take a breather. I turned you down.",
    "Resting in turns. The {side} ear is on break now.",
  ],
  earsThanks: [
    "There. Better already. Your ears will thank you.",
    "Turned it down. Listen like this, handsome.",
    "Quieter doesn't mean worse. Enjoy.",
    "Done. Your ears are safe now, damn it.",
  ],
});
// ------------------------------------------------------------ weather
Object.assign(en, {
  weatherNow: [
    "Weather - {place}: {sky}, {temp}. Reporting like a forecaster.",
    "{place}: {sky}, {temp}. Looked out the window for you, don't thank me.",
    "Report: {place}, {temp}, {sky}. Dress for it, damn it.",
    "Outside ({place}) it's {sky} now, {temp}. We live.",
    "Checked the sky - {place}: {sky}, {temp}.",
  ],
  rainStart: [
    "Oh, it's raining - {place}, {temp}. Got my umbrella out.",
    "Drip-drip. {place}: rain, {temp}. I'm under an umbrella, you're under a roof.",
    "It's pouring, bitch! {place}, {temp}. Good thing we're home.",
    "Rain's started. If you were going out - take an umbrella, {place} is getting wet.",
    "{place}: it's drizzling. {temp}. Perfect weather to go nowhere.",
    "Hear that? Rain. {place}, {temp}. I'm already under my umbrella.",
  ],
  rainStop: [
    "The rain stopped. Drying my umbrella.",
    "That's it, no more drops. You can crawl out, {place} is drying.",
    "Stopped pouring. Kind of boring without the drip-drip.",
    "Rain's over. {sky}, {temp}. Umbrella away.",
    "Done raining. Open a window, damn it.",
  ],
  storm: [
    "Thunderstorm! {place}, {temp}. Unplug the charger, just in case.",
    "It's thundering, bitch! I've got an umbrella, but that won't help.",
    "A storm. Save your work before the lights flicker.",
    "Kaboom! {place}: thunderstorm. I'm not scared. Almost.",
    "Lightning, thunder, {temp}. Stay inside, I've got you covered.",
  ],
  snowStart: [
    "It's snowing! {place}, {temp}. Catch the snowflakes.",
    "Snow! {place}: {temp}. Dress warm, damn it.",
    "Look - snow. I'm catching snowflakes, don't you catch a cold.",
    "{place} is getting buried in snow. {temp}. Cocoa time.",
  ],
  fog: [
    "Fog. {place} looks like milk. Can't see a thing, like in your code.",
    "{place}: fog, {temp}. Careful on the road.",
    "Thick fog. I can see you, the window can't.",
  ],
  frost: [
    "{place}: {temp}. That's not weather, that's a freezer, bitch.",
    "Frost, {temp}! Wear a hat or your ears will freeze off.",
    "{temp} outside. I'm sitting by the CPU to keep warm.",
  ],
});
